<a href="https://colab.research.google.com/github/vaishjah3/Assignments/blob/main/CNN_perception_map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import Adam

# Sample data generation function
def generate_sample_data(image_size=(100, 100), obstacle_size=(20, 20), num_samples=1000):
    samples = []
    for _ in range(num_samples):
        obstacle_x = np.random.randint(0, image_size[0] - obstacle_size[0])
        obstacle_y = np.random.randint(0, image_size[1] - obstacle_size[1])
        image = np.zeros(image_size)
        image[obstacle_x:obstacle_x+obstacle_size[0], obstacle_y:obstacle_y+obstacle_size[1]] = 1
        samples.append((image, (obstacle_x, obstacle_y)))
    return samples

# Generate sample data
image_size = (100, 100)
obstacle_size = (20, 20)
num_samples = 1000
data = generate_sample_data(image_size, obstacle_size, num_samples)

# Split data into train and validation sets
train_data = data[:800]
val_data = data[800:]

# Preprocess data
def preprocess_data(samples):
    X = np.array([sample[0] for sample in samples])
    y = np.array([sample[1] for sample in samples])
    X = X.reshape(-1, image_size[0], image_size[1], 1)  # Reshape for Conv2D
    y = y   # Normalize coordinates
    return X, y

X_train, y_train = preprocess_data(train_data)
X_val, y_val = preprocess_data(val_data)

# Define model
model = tf.keras.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(image_size[0], image_size[1], 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(2,name="my_dense_layer")  # 2 for x, y coordinates
])

# Compile model
model.compile(optimizer='adam', loss='mse')

# Train model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_val, y_val))




In [ ]:
X_train[0], y_train[0]

(array([[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],
 
        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],
 
        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],
 
        ...,
 
        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],
 
        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],
 
        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]]),
 array([ 8, 70]))

In [ ]:
model.input

<KerasTensor: shape=(None, 100, 100, 1) dtype=float32 (created by layer 'conv2d_9_input')>

In [ ]:
import tensorflow as tf

# Define the shape of the tensor
shape = (1, 100, 100, 1)

# Create a tensor filled with zeros
tensor = tf.zeros(shape, dtype=tf.float32)

# If you want to initialize it with random values instead:
#tensor = tf.random.normal(shape, dtype=tf.float32)

# Print the tensor shape and dtype
print("Tensor shape:", tensor.shape)
print("Tensor dtype:", tensor.dtype)

Tensor shape: (1, 100, 100, 1)
Tensor dtype: <dtype: 'float32'>


In [ ]:
tensor

In [ ]:
image=X_train[0]

In [ ]:
image = image.reshape(1, 100, 100, 1)

In [ ]:
model.predict(image)

1/1 [==============================] - 0s 158ms/step


array([[ 6.758006, 74.83145 ]], dtype=float32)